Algoritmo "digiteNumero2"

Var
n: inteiro

Inicio
 escreval("Digite um númro de 1 ao 5:")
 leia(n)
 
 escolha n
      caso 1
          escreval("um")
      caso 2
          escreval("dois")
      caso 3
          escreval("três")
      caso 4
          escreval("quatro")
      caso 5
          escreval("cinco")
      outrocaso
          escreval("Número Inválido")
 fimescolha

Fimalgoritmo